// <auto-generated />
namespace MedOffice.Migrations.PatientDBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pacjenci : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pacjenci));
        
        string IMigrationMetadata.Id
        {
            get { return "201804172031458_Pacjenci"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
