// <auto-generated />
namespace MedOffice.Migrations.AppointmentDBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Service_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Service_time));
        
        string IMigrationMetadata.Id
        {
            get { return "201805070833109_Service_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
